### ISSUE TITLE
run sh bin/startup.sh error  centos7 x64

### ISSUE THREAD

**Issue by yuanzl-1024** [geekidea/spring-boot-assembly#5]
[root@10-9-47-76 spring-boot-assembly]# sh bin/startup.sh
bin/startup.sh: line 2: $'\r': command not found
bin/startup.sh: line 15: $'\r': command not found
bin/startup.sh: line 18: $'\r': command not found
bin/startup.sh: line 21: $'\r': command not found
: No such file or directory: bin
: No such file or directory: ..
bin/startup.sh: line 31: $'\r': command not found
bin/startup.sh: line 35: $'\r': command not found
bin/startup.sh: line 42: $'\r': command not found
bin/startup.sh: line 45: $'\r': command not found
bin/startup.sh: line 49: $'\r': command not found
bin/startup.sh: line 52: $'\r': command not found
bin/startup.sh: line 128: syntax error: unexpected end of file
[root@10-9-47-76 spring-boot-assembly]#

**Comment by yuanzl-1024** [comment]
已解决，:set ff=unix 就好了...

**Comment by ANGLIOK** [comment]
不行啊，怎么搞的
